services:
  userfacing-api:
    image: userfacing-api:integration-tests
    pull_policy: build
    build:
      context: ${USERFACING_API_PATH:-../DECODE_Cloud_UserAPI}
      args:
        PYTHON_VERSION: 3.11.10
    restart: no
    ports:
      - 8000:8000
    volumes:
      - ~/.aws/credentials:/home/app/.aws/credentials
    env_file: .env
    environment:
      - AUTH=1
      - FILESYSTEM=local
      - S3_BUCKET=
      - S3_REGION=
      - USER_DATA_ROOT_PATH=./user_data
      - DATABASE_URL=sqlite:///./sql_app.db
      - DATABASE_SECRET=
      - WORKERFACING_API_URL=http://workerfacing-api:8001
      - INTERNAL_API_KEY_SECRET=not-secret
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_REGION=${COGNITO_REGION}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_SECRET=${COGNITO_SECRET}
      - APPLICATION_CONFIG_FILE=
      - EMAIL_SENDER_SERVICE=
      - EMAIL_SENDER_ADDRESS=
      - EMAIL_SENDER_API_KEY=
      - EMAIL_SENDER_SECRET_KEY=
      - FRONTEND_URL="http://frontend:8080"

  workerfacing-api:
    image: workerfacing-api:integration-tests
    pull_policy: build
    build:
      context: ${WORKERFACING_API_PATH:-../DECODE_Cloud_WorkerAPI}
      args:
        PYTHON_VERSION: 3.11.10
    restart: no
    ports:
      - 8001:8001
    volumes:
      - ~/.aws/credentials:/home/app/.aws/credentials
    env_file: .env
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - IS_PROD=0
      - FILESYSTEM=local
      - S3_BUCKET=
      - S3_REGION=
      - USER_DATA_ROOT_PATH=./user_data
      - QUEUE_DB_URL=sqlite:///./sql_queue.db
      - QUEUE_DB_SECRET=
      - MAX_RETRIES=2
      - TIMEOUT_FAILURE=300
      - RETRY_DIFFERENT=1
      - USERFACING_API_URL=http://userfacing-api:8000
      - INTERNAL_API_KEY_SECRET=not-secret
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_REGION=${COGNITO_REGION}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_SECRET=${COGNITO_SECRET}

  frontend:
    image: frontend:integration-tests
    pull_policy: build
    build:
      context: ${FRONTEND_PATH:-../DECODE_Cloud_UserFrontend}
    restart: no
    ports:
      - 8080:8080
    env_file: .env
    environment:
      - API_URL=http://userfacing-api:8000

  job-fetcher:
    image: job-fetcher:integration-tests
    pull_policy: build
    build:
      context: ${JOB_FETCHER_PATH:-../DECODE_Cloud_JobFetcher}
      args:
        PYTHON_VERSION: 3.11.10
    restart: no
    volumes:
      - ~/.aws/credentials/:/home/app/.aws/credentials
      - /var/run/docker.sock:/var/run/docker.sock
      - ./job_fetcher_data/:/data
    env_file: .env
    environment:
      - API_URL=http://workerfacing-api:8001
      - ACCESS_TOKEN=${ACCESS_TOKEN:-}
      - USERNAME=${EMAIL}
      - PASSWORD=${PASSWORD}
      - PATH_BASE=/data
      - PATH_HOST_BASE=./job_fetcher_data
      - TIMEOUT_JOB=30
      - TIMEOUT_STATUS=30
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
