name: Code checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  static_code_checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11.10'
    - name: Install poetry
      run: |
        POETRY_VERSION=$(grep -E '^requires-poetry = ' pyproject.toml | sed -E 's/requires-poetry = "(.*)"/\1/')
        pip install poetry==$POETRY_VERSION
    - name: Install dependencies
      run: poetry install
    - name: Ruff check
      run: poetry run ruff check .
    - name: Ruff format check
      run: poetry run ruff format --check .
    - name: Mypy check
      run: poetry run mypy .
